export const NHMP_FALLBACK_SNAPSHOT = {
  timestamp: "2026-04-12T16:11:57.415Z",
  sourceLabel: "Last known official NHMP snapshot",
  advisories: [
    {
      route: "M1 (Peshawar to Islambad Motorway)",
      sector: "Sector M1 (Peshawar to Islambad Motorway) Ph: 093-8490463 0331-5999130",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "E35 (Burhan to Thakot)",
      sector: "",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector M2North (Islambad to Kot Momin Motorway) Ph:051-4675190 051-4675291",
      sector: "Sector M2North (Islambad to Kot Momin Motorway) Ph:051-4675190 051-4675291",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M14 (Hakla to D.I.Khan)",
      sector: "Sector M14 (Hakla to D.I.Khan) Ph:045-9395055",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "(Col Sher khan to Chakdara)",
      sector: "Sector Swat Expressway (Col Sher khan to Chakdara) Ph:0346-9074406",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M2 (Kot Momin to Lahore )",
      sector: "Sector M2-South (Kot Momin to Lahore ) Ph: 048-6886112 0332-0521734",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M3 (Lahore to Abdul Hakeem)",
      sector: "Sector M3 (Lahore to Abdul Hakeem) Ph:0311-4881145",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M11 (00 Mehmood Booti to 91 Sambrial Toll Plaza Sialkot)",
      sector: "Sector M11 (00 Mehmood Booti to 91 Sambrial Toll Plaza Sialkot) Ph: 052-6300185",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M4 (Pindibhatiya-KM290 to Abdul Hakeem-KM89)",
      sector: "Sector M4 (Pindibhatiya-KM290 to Abdul Hakeem-KM89) Ph: 046-2526025",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M4 (Abdul Hakeem KM89 to Sher Shah KM00 )",
      sector: "Sub-Sector M4 (Abdul Hakeem KM89 to Sher Shah KM00 ) Ph:0318-7731203",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M5 (Sher Shah Multan-KM772 to Zahier Pir-KM579)",
      sector: "Sector-1 M5 (Sher Shah Multan-KM772 to Zahier Pir-KM579) Ph:0301-9316623",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "M5 (Zahir Pir KM579 to Rohri Toll Plaza KM386)",
      sector: "Sector-2 M5 (Zahir Pir KM579 to Rohri Toll Plaza KM386) Ph: 0315-4482532",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "(GT Road Peshawar to Islambad)",
      sector: "Sector North-I (GT Road Peshawar to Islambad) Ph:0923-695033",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector North-II (Islambad to Kharian) Ph:0544-226055 0544-226056",
      sector: "Sector North-II (Islambad to Kharian) Ph:0544-226055 0544-226056",
      status: "Weather : Partial Cloudy from Kharian Cantt (KM 1410) to Sawan (KM 1533).",
      severity: "cloudy",
      hasWarning: true,
    },
    {
      route: "Sector North-II (Islambad to Kharian) Ph:0544-226055 0544-226056",
      sector: "Sector North-II (Islambad to Kharian) Ph:0544-226055 0544-226056",
      status: "Lane Closed: from Sultania Hotel (KM 1460) to Sultania Hotel (KM 1460) due to Road Work (Road Side : South Bound 1st Lane )",
      severity: "closed",
      hasWarning: true,
    },
    {
      route: "(Kharian to Lahore )",
      sector: "Sector North-III (Kharian to Lahore ) Ph:055-6816200 055-6813500",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N-75 (Islamabad to Murree N-75)",
      sector: "Sector IMDC (Islamabad to Murree N-75) Ph:0304-9256202",
      status: "Weather : Rain from 13 (KM Satra meel) to 54 (KM Lower toppa).",
      severity: "rain",
      hasWarning: true,
    },
    {
      route: "(Lahore to Chichawatni)",
      sector: "Sector Central-I (Lahore to Chichawatni) Ph:044-2700669, 044-2700668",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector Central-II (Mian Chanu to Bahawalpur) Ph:0303-0984130, 061-6779130",
      sector: "Sector Central-II (Mian Chanu to Bahawalpur) Ph:0303-0984130, 061-6779130",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector Central-III (Ahmed Pur East to Sadiqabad) Ph:0324-5810744, 068-5678008, 068-5678010",
      sector: "Sector Central-III (Ahmed Pur East to Sadiqabad) Ph:0324-5810744, 068-5678008, 068-5678010",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N-5 (Rahim Yar Khan to Karachi)",
      sector: "Sector South-I (Kot Sabzal to Halani) Ph:071-9310878",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from chandan canal bridge (KM 268 to 269) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from near moro toll plaza (KM 321 to 326) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from tv booster to noorpur village (KM 331 to 332) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from tassi pump to nango shah (KM 333 to 335) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from kunda khahi to bhiriya bypass (KM 347 to 352) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from shah jamal to kandiaro toll plaza (KM 364 to 370) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "Sector South-II (Halani to Hala) Ph:024-4323494",
      sector: "Sector South-II (Halani to Hala) Ph:024-4323494",
      status: "Diversion : Traffic of the North Side diverted from salah rajper to halani (KM 375 to 380) due to Road Work",
      severity: "warning",
      hasWarning: true,
    },
    {
      route: "(Hala to Karachi New Sabzi Mandi)",
      sector: "Sector South-III (Hala to Karachi New Sabzi Mandi), LEW(Sohrab Goth to Agra Taaj) Ph:022-2109075",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N55 (Jamshoro - Bhan Saeedabad )",
      sector: "Sector N55-1 (Jamshoro - Bhan Saeedabad ) Ph:0254620097",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N55 (Bhan Saeedabad - Ratodero )",
      sector: "Sector N55-2 (Bhan Saeedabad - Ratodero ) Ph:074-4752944",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "Sector West-III (Kalat to Quetta) Ph:084-4210958",
      sector: "Sector West-III (Kalat to Quetta) Ph:084-4210958",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N10 (Gawadar to Makola )",
      sector: "Sector N10 (Gawadar to Makola ) Ph: 0333-0666581",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "N50 (Kuchlak ByPass to Killasaifullah Bypass )",
      sector: "Sector N50 (Kuchlak ByPass to Killasaifullah Bypass ) Ph: 082-3610204",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    },
    {
      route: "NHMP corridor",
      sector: "",
      status: "Road & Weather Clear",
      severity: "clear",
      hasWarning: false,
    }
  ],
};
